### ISSUE TITLE
TOTP Registration backend

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-totp-authenticator#1]
Handle the backend requests when registering the TOTP method.

ACs
- TOTP secret can be generated
- Codes can be validated
- No QR generation logic in the backend- we'll leave this to the front end
- Refactor existing logic to be compatible with new MFA module

Notes
- The following library has been previously recommended https://github.com/Spomky-Labs/otphp

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-mfa/pull/74
- [x] https://github.com/creative-commoners/silverstripe-webauthn/pull/2
- [ ] https://github.com/silverstripe/silverstripe-totp-authenticator/pull/4

**Comment by robbieaverill** [comment]
PRs posted to the description.

The MFA module has now got strong PHP 7 types and a 7.1 minimum, and contains an encryption adapter which defaults to using https://github.com/defuse/php-encryption.

The TOTP and WebAuthn modules have been updated to match this, and TOTP now uses https://github.com/Spomky-Labs/otphp to provide a provisioning URI for the QR code to the frontend, validate the user inputted TOTP code after having scanned it (via a React library to render the QR code), ask MFA to encrypt the secret and store it against the new registered method in the DB. TOTP also will register itself as unavailable as a registration method if you haven't defined the `SS_MFA_SECRET_KEY` environment variable in your project yet.

WebAuthn has been updated to register itself as an unavailable registration method when you aren't running HTTPS (it doesn't work without HTTPS anyway at the browser level).
