### ISSUE TITLE
"Register with authenticator app" MFA option is disabled and has notice "Unsupported: This method has not been configured yet."

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-totp-authenticator#112]
## Description
Regression tests have been executed on: SC PHP 7.4 Chrome GraphQL v3 Sink.
User doesn't have an ability to select "Register with authenticator app" and sees notice "Unsupported: This method has not been configured yet."

![TOTP_method.png](https://images.zenhubusercontent.com/6240ee9a7a0aac6d45cfd39d/652c7266-10f7-4e5c-a56d-2e350581cb21)

### Steps to reproduce
- I log in with administrator permissions
- I see the MFA introduction screen
- I click on "Get started"
- I should see a list of MFA methods
- I click on Register with authenticator app (disabled)
https://studio.cucumber.io/projects/301855/test-runs/758277/folder-snapshots/8007985/scenario-snapshots/28020693/test-snapshots/38195468

## PR

**Comment by maxime-rainville** [comment]
@sabina-talipova Can you double check that there's an MFA env variable on the production environement.

**Comment by sabina-talipova** [comment]
MFA environment variable was added. New tests have been done. Tests passed.
Issue is closed.

**Comment by michalkleiner** [comment]
One thing worth noting would be to check SCPS knowledge base or the MFA module's docs to highlight that the env variable is needed. We had several cases where SCPS support didn't add it until explicitly asked, even for a site being migrated from CWP.
