### ISSUE TITLE
Selecting TOTP after previously selecting WebAuthn breaks the UI

### ISSUE THREAD

**Issue by Cheddam** [silverstripe/silverstripe-totp-authenticator#19]
Steps to reproduce:

- Visit MFA initial registration UI
- Select 'Security Key' method, click Next
- Click Back, select 'Authenticator app', click Next
- App breaks

Looks like some state might not be getting put into place when expected.

**Comment by robbieaverill** [comment]
Reproduced

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/silverstripe-mfa/pull/200
