### ISSUE TITLE
TOTP registration screen

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-totp-authenticator#2]
TOTP registration screen for the authentication app.

Designs: https://projects.invisionapp.com/share/3PNSKZQYBJZ#/screens/321189813

ACs
- A user is able to complete registration with an authenticator app in these two screens
- Introduction text is static in the app
- QR code is included here
- Find out more link is pulled from the TOTP module.

Pull requests:

- [x] https://github.com/silverstripe/silverstripe-mfa/pull/76
- [x] https://github.com/silverstripe/silverstripe-totp-authenticator/pull/6

**Comment by robbieaverill** [comment]
I've added a lightweight shell of this in order to test the backend with #4, so this will mostly just be styling

**Comment by robbieaverill** [comment]
>Find out more link is pulled from the TOTP module.

Just noting that this isn't the case, we've designed it so that each authenticator can have its own support link. When we have a userhelp section for MFA in general we can obviously use the same link in each module though.

**Comment by robbieaverill** [comment]
PRs merged
