### ISSUE TITLE
isAvailable() relies on getenv() which ignores _ss_environment.php

### ISSUE THREAD

**Issue by indygriffiths** [silverstripe/silverstripe-totp-authenticator#28]
Bit of veeery minor feedback, but for local development I was expecting that adding a `define('SS_MFA_SECRET_KEY')` to my _ss_environment.php file would satisfy the requirement of having that defined in order to make the method available. 

`Method::isAvailable()` relies on `getenv()` which doesn't take into account any defines in _ss_environment.php, which took me a wee bit to work out. May be worth updating the docs or something about how it needs to be a proper envvar.

**Comment by robbieaverill** [comment]
Yep, we should be using constants in SS3, must’ve missed this during the backport

**Comment by robbieaverill** [comment]
The only tricky bit with this is that a bunch of our tests rely on being able to modify the environment variable's value repeatedly during tests. Given that we can't do that with constants, and that the constant is probably already defined in the project's environment file, we should probably nuke the tests, or modify them so the part that reads the constant is abstracted and mockable

**Comment by robbieaverill** [comment]
Since this is SS3 only, a quick fix would be to fall back to a constant if defined and no env var exists - that way the tests would still work

**Comment by robbieaverill** [comment]
Fix at https://github.com/silverstripe/silverstripe-totp-authenticator/pull/30

**Comment by ScopeyNZ** [comment]
Closed in #30
