### ISSUE TITLE
DOCs: using the secret key across environments

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-totp-authenticator#29]
For implementations on our commercial platforms, we've opted to share the MFA encryption key (`SS_MFA_SECRET_KEY`) as an environment variable between environments (UAT and Prod).

Perhaps it make sense to mention this in the docs for others to consider when implementing on their own hosting service.

_Raising as an issue, rather than a PR, to check that others think this is worthwhile._

**Comment by robbieaverill** [comment]
Go for it

**Comment by ScopeyNZ** [comment]
I think we should mention the fact that having different keys means data can not be distributed between environments but we should avoid providing specific advice. In many cases the UAT environment can (and maybe should) be considered a less secure environment - having a shared secret then is a _bad idea_.

**Comment by robbieaverill** [comment]
>I think we should mention the fact that having different keys means data can not be distributed between environments but we should avoid providing specific advice.

I'll do this as part of the documentation file "Security" I'm creating for https://github.com/silverstripe/silverstripe-mfa/issues/267

**Comment by robbieaverill** [comment]
Makes more sense in this repository actually

**Comment by robbieaverill** [comment]
Done in 24dd0d8 - reopen or make adjustment PRs if you'd like to amend =)
