### ISSUE TITLE
Stronger guidance on creating a secret key

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/silverstripe-totp-authenticator#43]
The docs outline that a secret key is required to encrypt the TOTP secret, but it doesn't give an example.

We should provide a recommended character length and level of entropy.

Current docs here: https://github.com/silverstripe/silverstripe-totp-authenticator#encryption-key

**Comment by chillu** [comment]
https://github.com/silverstripe/silverstripe-totp-authenticator/pull/54
