### ISSUE TITLE
Unhandled case: Site title can be null

### ISSUE THREAD

**Issue by adrhumphreys** [silverstripe/silverstripe-totp-authenticator#64]
In the `RegisterHandler` we have the method `start` and on [line 61](https://github.com/silverstripe/silverstripe-totp-authenticator/blob/6b516f73186a42f59fb75f823390ea0f571bedf0/src/RegisterHandler.php#L61) we set the issuer.

Code here is:
```
$totp->setIssuer(SiteConfig::current_site_config()->Title);
```

`setIssuer` expects a string value and no null values, where as `SiteConfig::current_site_config()->Title` can be a string or a null value

This means if your site has no site title then the MFA will break due to a null passed through to the `setIssuer`. This means you need to reimplement the whole `start` method just to change that line rather than extending it via `updateTotp` to set the issuer.

I'm not sure what the fix should be since the title usually needs to be relatively short for most apps but ideally we could change this to `$totp->setIssuer(SiteConfig::current_site_config()->Title ?? 'No issuer defined');` or some such

**Comment by robbieaverill** [comment]
Fix: cast it as a string

---

Could you give me an example of why would the site config title be empty?
