### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-totp-authenticator#70]
**ACs:**
- Upgrade composer dependencies so that totp can be composer installed on a local php environment without the use of the `--ignore-platform-reqs` flag
- Make any other code changes required for php8 support

It's likely that the following dependency will need to have a major version bump:

spomky-labs/otphp: ^9 upgrade to ^10

### PR
- [x] https://github.com/silverstripe/silverstripe-totp-authenticator/pull/82

**Comment by emteknetnz** [comment]
Apparently should be an easy upgrade - https://github.com/Spomky-Labs/otphp/blob/v10.0/doc/UPGRADE_v9-v10.md

**Comment by maxime-rainville** [comment]
Merged
